### ISSUE TITLE
The console of Powershell stopped while installing Python 2.7

### ISSUE THREAD

**Issue by inlacrimis** [TheBastionBot/BastionDocs#7]
i dont know how to explain, but powershell doesnt move anymore after saying python is installed, its been like 1 hour since im waiting for it to get installed, this is how it currently looks like https://vgy.me/9s6Xdk.png

everything else was fine.
i hope i can get a solution asap

**Comment by iamtraction** [comment]
The issue tracker is not for installation support, go to [Bastion HQ](https://discord.gg/fzx8fkt) instead.
